### ISSUE TITLE
Proposal: split cpphs in the library and the executable 

### ISSUE THREAD

**Issue by asr** [malcolmwallace/cpphs#1]
cpphs has two different and _independent_ uses: the library and the executable. For example, Agda uses the executable but not the library, and haskell-src-exts uses the library but not the executable. In fact, there are different Cabal fields for representing the different uses: `build-depends` for the library and `build-tools` for the executable. I suggest to split cpphs in the cpphs-library and the cpphs-executable.

**Comment by malcolmwallace** [comment]
But presumably the cpphs-executable package would depend on cpphs-library, so there would be no way to install just the executable, avoiding the library package?

**Comment by asr** [comment]
Right, but it is possible to install the library without installing the executable.

**Comment by asr** [comment]
Right, but it should be possible to install the library without installing the executable.

Blocking https://github.com/agda/agda/issues/1808.

**Comment by ndmitchell** [comment]
Cabal packages and easily include both 1 library and an executable in one - e.g. hlint, hoogle, shake etc. I don't see the advantages of two packages?

**Comment by asr** [comment]
Agda had a dependency which depends of the `cpphs` library and Agda also depends of the `cpphs` executable. This "double" dependency was generating a problem when installing Agda using the `--program-suffix` option of `cabal-install`. Since Agda currently doesn't indirectly depend of the `cpphs `library, I'm closing the issue.
