### ISSUE TITLE
head on empty list error

### ISSUE THREAD

**Issue by ndmitchell** [malcolmwallace/cpphs#13]
Given `Sample.hs` containing:

```
#ifndef
#endif
```

Running `cpphs Sample.hs` gives:

```
cpphs: Prelude.head: empty list
```

Originally reported by @RyanGlScott in https://github.com/ndmitchell/hlint/issues/355 with cpphs-1.20.5.

**Comment by malcolmwallace** [comment]
Fixed in cpphs-1.20.6
