### ISSUE TITLE
Stop using old-time

### ISSUE THREAD

**Issue by ndmitchell** [malcolmwallace/cpphs#15]
The package is hard to install and not required by most things. It would be good if cpphs switched to time, which makes the installation process on Windows a bit smoother.

**Comment by asr** [comment]
We have a similar request in Agda from our users on Windows (see https://github.com/agda/agda/issues/3223).

CC'ing @Saizan.

**Comment by Kamayuq** [comment]
I would support this request as it makes installing under windows a pain, especially if one does not want to install some sort of bash (which all have their own problems)

**Comment by ndmitchell** [comment]
Note that if you use Stack this "just works" - that's the easiest way to go.

**Comment by Kamayuq** [comment]
In this case true, but there are other cases where stack has problems (e.g. with the language server plugin) because there has been no release for latest GHC and Cabal. I believe it is desirable to have a low friction working Cabal build.

**Comment by malcolmwallace** [comment]
I just uploaded cpphs-1.20.9 to Hackage.  Apologies: I updated the package dependency locally a long time ago, but never got round to publishing it.

**Comment by Kamayuq** [comment]
Thank you!

**Comment by ndmitchell** [comment]
Thanks Malcolm!
