### ISSUE TITLE
Broken compilation on GHC 8.6.1

### ISSUE THREAD

**Issue by asr** [malcolmwallace/cpphs#18]
Using GHC 8.6.1 I'm getting various errors like this

```bash
$ cabal install --allow-newer
...
Building library for polyparse-1.12..
...
[ 8 of 18] Compiling Text.Parse       ( src/Text/Parse.hs, dist/build/Text/Parse.o )

src/Text/Parse.hs:230:20: error:
    • Could not deduce (Control.Monad.Fail.MonadFail (Parser Char))
        arising from a do statement
        with the failable pattern ‘'-'’
      from the context: Real a
        bound by the type signature for:
                   parseSigned :: forall a. Real a => TextParser a -> TextParser a
        at src/Text/Parse.hs:229:1-53
    • In a stmt of a 'do' block: '-' <- next
      In the first argument of ‘onFail’, namely
        ‘do '-' <- next
            commit (fmap negate p)’
      In the expression:
        do '-' <- next
           commit (fmap negate p)
          `onFail` do p
    |
230 | parseSigned p = do '-' <- next; commit (fmap negate p)
    |                    ^^^^^^^^^^^
```

The errors in `polyparse` are due to the implementation of the MonadFail proposal in GHC 8.6.1. See the reason for the errors and possible solutions [here](https://prime.haskell.org/wiki/Libraries/Proposals/MonadFail).

**Comment by asr** [comment]
Blocking https://github.com/agda/agda/issues/3254.

**Comment by tvh** [comment]
With this commit it works: https://github.com/factisresearch/polyparse/commit/ad194f2b7fcd88a34080c03548bd8f0386a76557.

**Comment by asr** [comment]
@malcolmwallace, could you release a new version of `polyparse` including the fix, please.

**Comment by mvoidex** [comment]
Any news?

**Comment by asr** [comment]
A new version of `polyparse` was released. See https://github.com/haskell-infra/hackage-trustees/issues/186.
